services:
  wine-ie8:
    build:
      context: ./build
    image: wine-ie8
    container_name: wine-ie8
    security_opt:
#      - no-new-privileges:true
      - seccomp:unconfined # October 15, 2020 https://github.com/jlesage/docker-firefox/blob/master/README.md#allowing-the-membarrier-system-call
#    ports:
#       - "5801:5800"
#       - "5901:5900"
    volumes:  #change the volumes acordingly to your needs
      - /mnt/data/apps-data/wine-ie8/config:/config
      - /mnt/data/apps-data/wine-ie8/Downloads:/config/downloads
      - /mnt/data/apps-data/wine-ie8/build/rootfs/startapp.sh:/startapp.sh
      - /dev/shm:/dev/shm
    environment:
      USER_ID: 0
      GROUP_ID: 0
     # TZ: $TZ
      UMASK: 002
      KEEP_APP_RUNNING: 1
      CLEAN_TMP_DIR: 1
      DISPLAY_WIDTH: 1280
      DISPLAY_HEIGHT: 720
      #Xvfb :0 -screen 0 1024x768x16 &
      #DISPLAY: 0

      # VNC_PASSWD: $FIREFOX_VNC_PASSWD # Since OAuth is enabled
#    networks:
#      iot_network:
#          ipv4_address: 192.168.40.40
    networks:
      macvlan-bridged-net:
          ipv4_address: 192.168.10.40

networks:
 macvlan-bridged-net:
   external: true
   name: macvlan-bridged-net

# networks:
#    media_network:
#     name: media_network
#     driver: macvlan
#     driver_opts:
#       parent: bond0
#     ipam:
#       #driver: dhcp
#       config:
#         - subnet: 192.168.10.0/24
#           gateway: 192.168.10.1
